# Generated by Django 6.0.6 on 2026-06-18 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('roll_number', models.CharField(max_length=20)),
                ('discipline', models.CharField(default='CSE', max_length=50)),
                ('batch_year', models.CharField(default='2025-26', max_length=20)),
                ('total_credits_required', models.IntegerField(default=173)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=20)),
                ('credits', models.IntegerField()),
                ('grade', models.CharField(max_length=5)),
                ('semester', models.IntegerField()),
                ('basket', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.student')),
            ],
        ),
    ]
