# Generated by Django 6.0.6 on 2026-07-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_completedcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
