# Generated by Django 6.0.6 on 2026-07-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_semesterplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='foundation_program',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ge_course_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ge_course_2',
            field=models.BooleanField(default=False),
        ),
    ]
